---
title: "main"
author: "Reza Dwi Utomo"
date: "23/03/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Langkah pre-processinh untuk yanh scotty:

1. Floor_date (rounding data date menjadi hourly)
2. grouping dan summarise dari datetime dan src_area kemudian dapet kolom demand
3. time series padding

floor_date library lubridate
untuk padding time series dari library padr::pad()

Mas itu kayaknya src_sub_area untuk Scotty time series
kalo liat test data setnya

```{r message=FALSE}
library(tidyverse)
# library(ggplot2)
library(ggfortify)
library(lubridate)
library(purrr)
```


```{r}
scotty <- read.csv("data/data-train.csv")
scotty
```

```{r}
scotty <- scotty %>% select(start_time, src_sub_area)
scotty$start_time <- ymd_hms(scotty$start_time)
```

```{r}
scotty <- scotty %>% 
  mutate(datetime = floor_date(x = .$start_time, unit = "hour"))

```

```{r}
scotty <- scotty %>% 
  group_by(src_sub_area, datetime) %>% 
  summarise(demand = n()) %>% 
  ungroup()
```

```{r}
min_date <- min(scotty$datetime)
max_date <- max(scotty$datetime)

start_val <- make_datetime(year = year(min_date), month = month(min_date), day = day(min_date), hour = hour(min_date))
end_val <- make_datetime(year = year(max_date), month = month(max_date), day = day(max_date), hour = hour(max_date))

scotty_pad <- padr::pad(x = scotty, start_val = start_val, end_val = end_val)
```

```{r}
scotty_pad$demand <- replace_na(scotty_pad$demand, 0)
```

```{r}
sxk97 <- scotty_pad %>% 
  filter(src_sub_area == "sxk97") %>%
  select(datetime, demand)
```

```{r}
sxk97_ts <- ts(sxk97$demand, frequency = 24)
tseries::adf.test(sxk97_ts)
```

```{r}
sxk97_ts %>% autoplot()
```

```{r}
sxk97_decom <- decompose(x = sxk97_ts, type = "additive")
decompose(x = sxk97_ts, type = "additive") %>% autoplot()
```

```{r}
sxk97_ets <- forecast::ets(y = sxk97_ts, model = "ZZZ")
shapiro.test(sxk97_ets$residuals)
Box.test(sxk97_ets$residuals)
```


```{r}
# split train-validation 1 seasonal
train <- head(sxk97_ts, length(sxk97_ts) - 24 * 7)
validation <- tail(sxk97_ts, 24 * 7)
```

```{r}
model_holt_ts<- HoltWinters(train, seasonal = "additive")
forecast_holt <- forecast::forecast(model_holt_ts, h = 24 * 7)
MLmetrics::MAE(y_pred = forecast_holt$mean, y_true = validation)
TSstudio::plot_forecast(forecast_holt, title = "Model Complex Seasonality")
```

```{r}
TSstudio::test_forecast(actual = sxk97_ts, forecast.obj = forecast_holt,
                        train = train, test = validation)
```

```{r}
model_sarima <- forecast::auto.arima(train)
forecast_sarima <- forecast::forecast(model_sarima, h = length(validation))
TSstudio::plot_forecast(forecast_sarima)
MLmetrics::MAE(y_pred = forecast_sarima$mean, y_true = validation)
```

```{r}
model_manualArima <- arima(train, order = c(1,0,2))
forecast_sarima <- forecast::forecast(model_manualArima, h = length(validation))
TSstudio::plot_forecast(forecast_sarima)
MLmetrics::MAE(y_pred = forecast_sarima$mean, y_true = validation)
```

```{r}
summary(model_sarima)
```

```{r}
TSstudio::test_forecast(actual = sxk97_ts, forecast.obj = forecast_sarima,
                        train = train, test = validation)
```

```{r}
forecast::msts(data = sxk97$demand, seasonal.periods = c(24, 24*7)) %>% 
  forecast::mstl() %>% 
  autoplot()

sxk97_msts <- forecast::msts(data = sxk97$demand, seasonal.periods = c(24, 24*7))
sxk97_mstsLog <- log(sxk97_msts)
sxk97_mstsLog %>% forecast::mstl() %>% 
  autoplot()
```

```{r}
boxplot(sxk97_mstl[,5])
max(sxk97_mstl[,5], na.rm = T)
```

```{r}
sxk97_mstl <- forecast::mstl(sxk97_mstsLog)
shapiro.test(sxk97_mstl[,5])
Box.test(sxk97_mstl[,5])
```


```{r}
# split train-validation 2 seasonal
train_2 <- head(sxk97_msts, length(sxk97_msts) - 24 * 7)
validation_2 <- tail(sxk97_msts, 24 * 7)
```

```{r}
model_holt_msts<- HoltWinters(train_2)
forecast_holt2 <- forecast::forecast(model_holt_msts, h = 24 * 7)
MLmetrics::MAE(y_pred = forecast_holt2$mean, y_true = validation_2)
plot_forecast(forecast_holt2)
```

```{r}
forecast_holt2$mean %>% autoplot() + autolayer(validation_2)
```

```{r}
TSstudio::test_forecast(actual = sxk97_msts, forecast.obj = forecast_holt2,
                        train = train_2, test = validation_2)
```

```{r}
model_sarima2 <- forecast::auto.arima(train_2)
forecast_sarima2 <- forecast::forecast(model_sarima2, h = 24 * 7)
TSstudio::plot_forecast(forecast_sarima2)
MLmetrics::MAE(y_pred = forecast_sarima2$mean, y_true = validation_2)
```

```{r}
summary(model_sarima2)

train_2 %>% autoplot()
forecast_sarima2$mean %>% autoplot() + autolayer(validation_2)
```

```{r}
model_sarima2$residuals %>% shapiro.test()# Box.test()# tseries::adf.test()
hist(model_sarima2$residuals, breaks = 50)
forecast_sarima2$fitted %>%  autoplot() + autolayer(validation_2)
```

```{r}
TSstudio::test_forecast(actual = sxk97_msts, forecast.obj = forecast_sarima2,
                        train = train_2, test = validation_2)
```

```{r}
model_sarima3 <- arima(train_2, order = c(2,0,3),
                       seasonal = list(order = c(1,0,3), period = 24), method = "ML")
forecast_sarima3 <- forecast::forecast(model_sarima3, h = 24 * 7)
TSstudio::plot_forecast(forecast_sarima3)
MLmetrics::MAE(y_pred = forecast_sarima3$mean, y_true = validation_2)
```

```{r}
fit <- forecast::auto.arima(train_2, max.p = 5 , 
                            max.q = 5, max.P = 5, max.Q = 5, max.d = 3,
                            seasonal = TRUE, ic = 'aicc')
fore <- forecast::forecast(fit, h = 24 * 7)
MLmetrics::MAE(y_pred = fore$mean, y_true = validation_2)
```

```{r}
forecast::tsdisplay(train_2, lag.max = 96)
```

p: 1, 2
d: 0
q: 0

p: 1, 2
d: 0
q: 1, 2, 3, 4, 5

P: 1
D: 0
Q: 1, 2, 3

```{r}

```


```{r}
md_all <- TSstudio::train_model(input = sxk97_msts, 
                          horizon = 12,
                          methods = list(
                            arima = list(method = "auto.arima"),
                            holtwinter = list(method = "HoltWinters")
                          ), 
                          train_method = list(
                            partitions = 6,
                            sample.out = 12,
                            space = 3
                          ))
```

```{r}

```

```{r}
scotty_ts <- ts(scotty_pad$demand, frequency = 24*7*4)
head(scotty_ts)
purrr::
```


```{r}
(dim(train)[1]):dim(sxk97)[1]
idx <- sxk97$datetime[(n+1):N]
pred <- data.frame(idx = idx, y_pred = predictions, y_true = sxk97$demand[(n+1):N])

library(plotly)
ggplotly(ggplot(data = pred, mapping = aes(x = idx)) + 
         geom_line(aes(y = y_pred), color = "blue", show.legend = T) + 
         geom_line(aes(y = y_true), color = "green", show.legend = T)) 
  # labs(x = "Date")
      

MLmetrics::MAE(y_pred = pred$y_pred, y_true = pred$y_true)
```

```{r}
sxk9e <- scotty_pad %>% 
  filter(src_sub_area == "sxk9e") %>%
  select(datetime, demand)
```

```{r}
# tes = diff(sxk9e$demand[(nrow(sxk9e)-1):nrow(sxk9e)], differences = 1)
tes <- diff(tail(sxk97$demand, 24*7), differences = 1)
tes <- lags(tes, k=1)

sxk97_lag <- lags(diff(sxk97$demand, differences = 1), k = 1)

std_test  = ((tes - min(sxk97_lag) ) / (max(sxk97_lag) - min(sxk97_lag)  ))
scaled_test = std_test *(1 -(-1)) + (-1)

scaler= c(min =min(sxk97_lag), max = max(sxk97_lag))
```

```{r}
# L = length(x_test)
x_test <- scaled_test$`x-1`
L = 24*7
dim(x_test) = c(length(x_test), 1, 1)

# scaler = Scaled$scaler

predictions = numeric(L)
X = x_test[1 , , ]
for(i in 1:L){
  # X = x_test[i , , ]
  dim(X) = c(1,1,1)
  # forecast
  yhat = model %>% predict(X, batch_size=batch_size)
  
  # looping
  X <- yhat
  
  # invert scaling
  yhat = inverter(yhat, scaler,  c(-1, 1))
  
    # invert differencing
  # yhat  = yhat + Series[(n+i)]
  
  # save prediction
  predictions[i] <- yhat
}
# nrow(sxk97)-length(tes)
preds <- diffinv(predictions, xi = sxk97$demand[1438])
```

```{r}
predictions
```

```{r}
idx <- tail(sxk97$datetime, 24*7+1)
pred2 <- data.frame(idx = idx, y_pred = predictions, y_true = tail(sxk97$demand, 24*7+1))

ggplotly(ggplot(data = pred2, mapping = aes(x = idx)) + 
         geom_line(aes(y = y_pred), color = "blue", show.legend = T) + 
         geom_line(aes(y = y_true), color = "green", show.legend = T)) 
```

